### ISSUE TITLE
Usabilla SDK in plugin not compatible with Xcode 11

### ISSUE THREAD

**Issue by SebasWebDev** [usabilla/usabilla-u4a-cordova#32]
Hi,

When compiling an app with `usabilla-cordoba` plugin as dependency the build fails due to the following error:
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: <app_path>/platforms/ios/Pods/Usabilla/Usabilla.framework/Modules/Usabilla.swiftmodule/x86_64.swiftmodule

It would be necessary to have a new version of the SDK compiled with Xcode 11 which contains the version 5.1 of Swift.

Thanks you.

**Comment by torkvell** [comment]
Hi @SebasWebDev,

This happens due to a difference in the compiler version used for our SDK and the compiler version you have in your Xcode you're trying to build with. To fix this you have to make sure the ```Usabilla.framework``` file are compiled with the same compiler you have on your end. You can find the correctly compiled version in our iOS repository for each release, in your case v6.4.2: 
![2019-11-07 at 12 22](https://user-images.githubusercontent.com/40064170/68385095-58196d80-0159-11ea-8a92-956285e7d04d.png)
[https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases)

To know which version the framework file are build with you can inspect the Swift header file:
![2019-11-07 at 12 21](https://user-images.githubusercontent.com/40064170/68384989-21435780-0159-11ea-862a-566d4ed00aa6.png)

You then have to replace the downloaded framework file with the one you have locally:
![2019-11-07 at 12 26](https://user-images.githubusercontent.com/40064170/68385345-d70ea600-0159-11ea-85cc-12e4e103a8ce.png)

I hope this helps you in moving forward. If there is anything else we can assist with, please let us know.
